language: java
sudo: false

os: linux
dist: bionic

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/

install: true

script: ./gradlew --info build

deploy:
  # Deploy snapshots on every commit pushed to master
  - provider: script
    script: ./gradlew uploadPublished -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD
    skip_cleanup: true
    on:
      branch: master

  # Deploy releases on every tag push
  - provider: script
    script: bash .ci/deploy.sh
    skip_cleanup: true
    on:
      tags: true